import numpy as np
import pyvista as pv


def generate_cube_volume(dimensions=(50, 50, 50),
                         cube_bounds=(15, 35, 15, 35, 15, 35),
                         spacing=(1.0, 1.0, 1.0),
                         origin=(0.0, 0.0, 0.0)):
    """
    Generate a simple 3D volume containing a solid cube in the middle.

    Parameters:
    -----------
    dimensions : tuple of int
        The size of the volume in the (X, Y, Z) dimensions.
    cube_bounds : tuple of int
        The region within the volume that will be assigned the value 1.
        This is specified as (x_start, x_end, y_start, y_end, z_start, z_end).
        Everything else outside this region will remain 0.
    spacing : tuple of float
        The spacing between voxels in each dimension. For example, (1.0, 1.0, 1.0)
        indicates each voxel is 1 unit apart in X, Y, and Z.
    origin : tuple of float
        The origin (0,0,0) or any custom coordinate where the volume starts.

    Returns:
    --------
    grid : pv.ImageData
        A PyVista ImageData object containing the generated volume data.
    data : numpy.ndarray
        The raw 3D NumPy array of the volume. Values inside the cube region are 1,
        and 0 elsewhere.
    """
    # Create a 3D NumPy array initialized to zeros
    data = np.zeros(dimensions)
    x_start, x_end, y_start, y_end, z_start, z_end = cube_bounds

    # Assign the value 1 to the specified cube region
    data[x_start:x_end, y_start:y_end, z_start:z_end] = 1.0

    # Create a PyVista ImageData object to represent the volume
    grid = pv.ImageData(dimensions=dimensions, spacing=spacing, origin=origin)

    # Flatten the data in Fortran order (column-major) to match VTK's internal requirements
    grid.point_data["values"] = data.flatten(order="F")

    return grid, data


def extract_iso_surface(grid, iso_value):
    """
    Extract an isosurface (3D surface) from the given volume using a specified threshold.

    Parameters:
    -----------
    grid : pv.ImageData
        The PyVista ImageData object containing the volume.
    iso_value : float
        The threshold (iso-value) to extract the surface.

    Returns:
    --------
    pv.PolyData
        The resulting 3D surface mesh generated by the contour operation.
    """
    return grid.contour([iso_value])


def visualize_3d_model(iso_surface):
    """
    Visualize a 3D mesh (isosurface) using PyVista's Plotter.
    Adds custom lighting and optional shadows.

    Parameters:
    -----------
    iso_surface : pv.PolyData
        The 3D surface mesh to visualize.
    """
    # Create a PyVista Plotter for interactive rendering
    plotter = pv.Plotter()

    # Add the isosurface mesh to the scene
    plotter.add_mesh(
        iso_surface,
        color='white',
        show_edges=True,
        edge_color='black',
        smooth_shading=True
    )

    # Create a headlight (light source that follows the camera)
    head_light = pv.Light(light_type='headlight')
    plotter.add_light(head_light)

    # Create a custom light source positioned far away, targeting a specific point
    custom_light = pv.Light(
        position=(10000, 10000, 10000),  # Light position in 3D space
        focal_point=(-10, -10, -10),  # The point the light is focused on
        color='red',  # The color of the light
        intensity=1.0,  # The brightness of the light
        light_type='camera light'  # 'camera light' moves with the camera
    )
    plotter.add_light(custom_light)

    # Add a coordinate axes to the scene
    plotter.add_axes()

    # Enable shadows (may reduce rendering performance)
    plotter.enable_shadows()

    # Display the interactive window
    plotter.show()


def main():
    """
    Main function to generate a synthetic volume with a cube, extract its isosurface,
    apply smoothing, and then visualize it in 3D.
    """
    # Define the overall volume dimensions
    dimensions = (50, 50, 50)

    # Define the bounds for the cube inside the volume
    cube_bounds = (15, 35, 15, 35, 15, 35)

    # Set the spacing and origin for the volume
    spacing = (1.0, 1.0, 1.0)
    origin = (0.0, 0.0, 0.0)

    # Generate the volume and retrieve the raw NumPy data
    grid, data = generate_cube_volume(dimensions, cube_bounds, spacing, origin)

    # Choose an iso-value that extracts the boundary of the cube
    iso_value = 0.5
    print(f"Using iso_value: {iso_value:.3f}")

    # Extract the 3D isosurface from the volume
    iso_surface = extract_iso_surface(grid, iso_value)

    # Smooth the resulting mesh for a cleaner surface (optional)
    smoothed_surface = iso_surface.smooth(n_iter=300, relaxation_factor=1)

    # Visualize the smoothed isosurface in 3D
    visualize_3d_model(smoothed_surface)


if __name__ == "__main__":
    main()
